name: CI/CD Pipeline Website Momee

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14.0' # Ubah ke versi Node.js yang Anda gunakan

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

  deploy-to-server:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PROD_SERVER_SSH_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.PROD_SERVER_IP }} >> ~/.ssh/known_hosts
    
    - name: Deploy to Development Server
      env:
        SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
        SERVER_USERNAME: ${{ secrets.PROD_USERNAME}}
      run: |
        ssh $SERVER_USERNAME@$SERVER_IP 'export NVM_DIR="$HOME/.nvm" && source "$NVM_DIR/nvm.sh" && nvm use v20.14.0 && cd ~/Capstone-Web-Promotional && git pull && npm install && npm run build && pm2 restart web-momee && pm2 describe web-momee'
